// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MyX5_snM_103FEY82N4KGGBswjAXQhU',
    appId: '1:803726674093:web:fff3dcf60965be66fa5e24',
    messagingSenderId: '803726674093',
    projectId: 'buzzerapp-abd6d',
    authDomain: 'buzzerapp-abd6d.firebaseapp.com',
    storageBucket: 'buzzerapp-abd6d.appspot.com',
    measurementId: 'G-NWLJ1F853R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiwab-f4DmKm1jZ4dYtTlUzs04vPGD_0',
    appId: '1:803726674093:android:a26dc10510155e7efa5e24',
    messagingSenderId: '803726674093',
    projectId: 'buzzerapp-abd6d',
    storageBucket: 'buzzerapp-abd6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfG08i4KIJ7J2ydXGrcvx5TrBjJwBCTY',
    appId: '1:803726674093:ios:678e76b691ad4058fa5e24',
    messagingSenderId: '803726674093',
    projectId: 'buzzerapp-abd6d',
    storageBucket: 'buzzerapp-abd6d.appspot.com',
    iosBundleId: 'com.codemire.buzzer.buzzerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfG08i4KIJ7J2ydXGrcvx5TrBjJwBCTY',
    appId: '1:803726674093:ios:a5ff53b2270fe2bafa5e24',
    messagingSenderId: '803726674093',
    projectId: 'buzzerapp-abd6d',
    storageBucket: 'buzzerapp-abd6d.appspot.com',
    iosBundleId: 'com.codemire.buzzer.buzzerApp.RunnerTests',
  );
}
